In [1]:
import numpy as np
import pandas as pd
from renom.utility import completion

In [4]:
data_size = 10000
x1 = np.random.randint(0, 500, data_size).reshape(-1, 1)
print(x1)
x2 = x1 + 10
print(x2)
x3 = np.random.randint(0, 500, data_size).reshape(-1, 1)
print(x3)
x4 = np.random.randint(0, 500, data_size).reshape(-1, 1)
print(x4)
x5 = np.random.choice(["One", "Two", "Three"], data_size, replace=True).reshape(-1, 1)
print(x5)
x6 = np.random.choice(["Four", "Five"], data_size, replace=True).reshape(-1, 1)
print(x6)
x = np.concatenate((x1, x2), axis=1)
x = np.concatenate((x, x3), axis=1)
x = np.concatenate((x, x4), axis=1)
x = np.concatenate((x, x5), axis=1)
x = np.concatenate((x, x6), axis=1)
print(x)

[[215]
 [499]
 [244]
 ...
 [206]
 [266]
 [139]]
[[225]
 [509]
 [254]
 ...
 [216]
 [276]
 [149]]
[[140]
 [ 35]
 [254]
 ...
 [227]
 [471]
 [314]]
[[  0]
 [293]
 [116]
 ...
 [ 78]
 [294]
 [480]]
[['Two']
 ['One']
 ['One']
 ...
 ['One']
 ['Two']
 ['Two']]
[['Four']
 ['Four']
 ['Four']
 ...
 ['Five']
 ['Five']
 ['Four']]
[['215' '225' '140' '0' 'Two' 'Four']
 ['499' '509' '35' '293' 'One' 'Four']
 ['244' '254' '254' '116' 'One' 'Four']
 ...
 ['206' '216' '227' '78' 'One' 'Five']
 ['266' '276' '471' '294' 'Two' 'Five']
 ['139' '149' '314' '480' 'Two' 'Four']]


In [3]:
missing_idx = np.random.permutation(data_size)
missing_idx1 = missing_idx[:1000]
missing_idx2 = missing_idx[-1010:]
missing_idx3 = missing_idx[2000:3050]
df = pd.DataFrame(x)
df.columns = ["x1", "x2", "x3", "x4", "x5", "x6"]
df = df.astype({"x1":float, "x2":float, "x3":float, "x4":float, "x5":str, "x6":str})
X_complete = df.values
df.loc[df["x2"]<50, "x1"] = np.nan
df.iloc[list(missing_idx1), 2] = np.nan
df.iloc[list(missing_idx2), 4] = np.nan
df.iloc[list(missing_idx3), 5] = np.nan
X_incomplete = df.values
X_filled = completion(X_incomplete, mode="mice", impute_type="col")
X_filled

[MICE] Completing matrix with shape (10000, 6)


/Users/yuto.maejima/work/projects/renom_tutorial/ReNom/renom/layers/loss/sigmoid_cross_entropy.py:18: RuntimeWarning: overflow encountered in exp
  z = 1. / (1. + np.exp(to_value(-lhs)))
/Users/yuto.maejima/work/projects/renom_tutorial/ReNom/renom/core.py:1341: RuntimeWarning: overflow encountered in exp
  ret = getattr(ufunc, method)(*new_inputs, **kwargs)


[MICE] Starting imputation round 10/60, elapsed time 116.611
[MICE] Starting imputation round 20/60, elapsed time 231.147
[MICE] Starting imputation round 30/60, elapsed time 353.679
[MICE] Starting imputation round 40/60, elapsed time 472.848
[MICE] Starting imputation round 50/60, elapsed time 590.849
[MICE] Starting imputation round 60/60, elapsed time 713.278


array([[133.0, 143.0, 151.0, 248.0, 'One', 'Five'],
       [3.8101701469160014, 11.0, 37.0, 221.0, 'One', 'Four'],
       [172.0, 182.0, 407.0, 238.0, 'Two', 'Four'],
       ...,
       [191.0, 201.0, 349.0, 27.0, 'Two', 'Four'],
       [346.0, 356.0, 220.0, 44.0, 'Three', 'Five'],
       [32.51599940949011, 39.0, 366.0, 132.0, 'Three', 'Four']],
      dtype=object)