In [1]:
import numpy as np
from renom.utility import interpolate

In [2]:
x = [[2.0, 3.0, 5.0], [3.0, np.nan, 8.0], [6.0, np.nan, 9.0],[7.0, 9.0, np.nan], [8.0, 10.0, 10.0], [10.0, 12.0, 14.0]]
x

[[2.0, 3.0, 5.0],
 [3.0, nan, 8.0],
 [6.0, nan, 9.0],
 [7.0, 9.0, nan],
 [8.0, 10.0, 10.0],
 [10.0, 12.0, 14.0]]

In [7]:
x_interp = interpolate(x, mode="linear")
x_interp

5.0

In [4]:
x_interp = interpolate(x, mode="spline")
x_interp

array([[ 2.        ,  3.        ,  5.        ],
       [ 3.        ,  6.4       ,  8.        ],
       [ 6.        ,  8.1       ,  9.        ],
       [ 7.        ,  9.        ,  9.03571429],
       [ 8.        , 10.        , 10.        ],
       [10.        , 12.        , 14.        ]])

In [5]:
x_interp = interpolate(x, mode="constant", constant=0.0)
x_interp

array([[ 2.,  3.,  5.],
       [ 3.,  0.,  8.],
       [ 6.,  0.,  9.],
       [ 7.,  9.,  0.],
       [ 8., 10., 10.],
       [10., 12., 14.]])

In [6]:
x_interp = interpolate(x, mode="nearest_index")
x_interp

array([[ 2.,  3.,  5.],
       [ 3.,  3.,  8.],
       [ 6.,  9.,  9.],
       [ 7.,  9.,  9.],
       [ 8., 10., 10.],
       [10., 12., 14.]])